ui: tape
concurrency: 1
browsers:
  - name: chrome
    version: latest
  - name: ie
    version: 9..latest
  - name: firefox
    version: 25..latest
  - name: ipad
    version: 4.3..latest
  - name: android
    version: 4.0..latest
  - name: opera
    version: 11..latest
  - name: safari
    version: 6..latest
